### ISSUE TITLE
Feature Request: Check and Host Annotations Support

### ISSUE THREAD

**Issue by seifer44** [sensu/sensu-email-handler#46]
The ability to add in recipients [to a single email](https://github.com/sensu/sensu-email-handler/pull/43) by appending them onto the To, CC, or BCC field, would be beneficial. Utilizing [check](https://docs.sensu.io/sensu-go/latest/reference/checks/#metadata-attributes) or [host](https://docs.sensu.io/sensu-go/latest/reference/agent/#general-configuration-flags) annotations would probably be a good way to do this. This would allow teams and users to "subscribe" to the handlers in a more flexible way, and would cut down on the number of separate handlers that may, otherwise, be required.

```
annotations:
  sensu.io.plugins.email.config.ccEmail: teamWidget@example.com
  sensu.io.plugins.email.config.toEmail: tier1WidgetOps@example.com
  sensu.io.plugins.email.config.bccEmail: secretOps@example.com
```

**Example:** Disk checks normally go to the server team, but teamWidget would like to be CCed onto disk check alerts for their servers only. Their servers could have client annotations set up, without requiring separate checks and handlers to be configured.

The appending portion of this feature request this may conflict with the [override behavior currently exhibited in filtering](https://docs.sensu.io/sensu-go/latest/guides/contact-routing/#entities). Regardless, annotation support of any sort would be a nice feature.

The downside to this approach is in the event you have 2+ email handlers already configured for a check. Both handlers would look at the annotation configuration above, and the annotated recipients may receive two or more email notifications, instead of one. This could be avoided by having a `sensu.io.plugins.email.config.handlerName` configuration available in the annotations, but then this approaches another complex way of setting up the same thing normal handlers are designed for.

This is a good discussion piece, if nothing else :)
